name: Run Node.js tests

# Sự kiện nào sẽ kích hoạt workflow này
on:
  push:
    branches:
      - main # Workflow sẽ chạy khi có thay đổi được đẩy lên nhánh 'main'

jobs:
  build:
    runs-on: ubuntu-latest # Chạy trên môi trường Ubuntu mới nhất

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Lấy mã nguồn từ kho lưu trữ

      - name: Set up Node.js
        uses: actions/setup-node@v2 # Thiết lập môi trường Node.js
        with:
          node-version: "22" # Sử dụng phiên bản Node.js 22

      - name: Install dependencies
        run: npm ci # Cài đặt các phụ thuộc của dự án

      - name: Run tests
        run: npm test # Chạy các bài kiểm tra của dự án
